### ISSUE TITLE
ESB - Finish adding more daily quests and start a rotation.

### ISSUE THREAD

**Issue by Deathinflames** [Deathinflames/DoD#18]
I've left the current set of daily quests to see if they will reset under certain circumstances as the days move forward, such as a player starting a quest and not completing it.

**Comment by Deathinflames** [comment]
The quests will randomly change as more quests become available for testing. As soon as a full week of quests are available, they will start rotating daily and more quests will continue to be added.

**Comment by Nightwolf3218** [comment]
Modification suggestion for current quests:

Villager Murderer - Change name to Serial Killer

Cookie Monster - Reduce Cookie crafting from 600 to 300.

**Comment by Deathinflames** [comment]
Finished adding a total of 21 quests to start a rotation.

Renamed Villager Murderer quest to Serial Killer
Added a new step to Cookie Monster quest to give crafted cookies. (<3 Fal)
