### ISSUE TITLE
ESB - Advanced crafting

### ISSUE THREAD

**Issue by Deathinflames** [Deathinflames/DoD#19]
This perk is immediately available to all and should be something the player gets access to a little later on, perhaps rank 5 as rank 6 is when players can obtain end-game island perks?

**Comment by Nightwolf3218** [comment]
I have a small suggestion to help put this at Rank 4 or 5.

First move /hat from Rank 4 to Rank 2 (this is cosmetic and really should be fairly easy to get by comparison).  

Rank 5 currently has /medic.  Maybe move this to Rank 4 and give access to advanced crafting at 5 or leave /medic at Rank 5 and give advanced crafting to players at 4.

**Comment by Deathinflames** [comment]
This functionality has been replaced with "Crafting Stations" and the Advanced Workbench is now deprecated. The Advanced Workbench will still be accessible however it will eventually be phased out completely.

> A crafting station is a GUI which grants players access to custom recipes. There are two types of recipes: **crafting recipes** which players can use to create new items and **upgrading recipes** which players can use to upgrade their weapons/armors.

These custom recipes may require specific ingredients (vanilla or items from MI) and conditions, including level, class and permission conditions. Crafting recipes may also have a crafting time, which is essentially a delay players need to wait before claiming the crafted item. These items go in the crafting queue and can be claimed whenever the player opens the crafting station again later.
