### ISSUE TITLE
ESB - /vote

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#27]
Have /vote either being up the vote gui like usb had, or give the list of vote sites.
/vote sites doesn't list our vote site links.
/vote rewards lists default example rewards.

**Comment by DingoKing** [comment]
/vote sites updated to show our current vote sites (TopG, Minecraft MP, and PlanetMinecraft).
/vote rewards updated to show the current rewards (1 vote crate and its contents, and the monthly rewards for 3, 15, 30, and 45 votes).

Still need to change "/vote" if we want to do that.

**Comment by Deathinflames** [comment]
Updated /vote :)
