### ISSUE TITLE
ESB - Wiki and Shop Additions

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#28]
Add "/is team trust" and "/is team coop" commands to Island Commands in Island Information
Add info on "/vs toggle" aka Void Save, maybe in Misc Features.
Add buttons in /shop for the Dungeon Shop and Player Auction House. (/ah). Perhaps also an info hover for "/trade <player>" and "/tfly pay <player> [h] [m] [s]"

**Comment by Deathinflames** [comment]
Updated these menus :)
