### ISSUE TITLE
ESB - Auto Farmer can't be upgraded

### ISSUE THREAD

**Issue by Rockheadryan** [Deathinflames/DoD#30]
**Describe the bug**
There's no upgrade buttons in the auto farmer gui
**To Reproduce**
1. Place down end rod
2. Right click
3. Discover that there is no upgrade button

**Expected behavior**
It's expected for upgrade buttons to be there

**Minecraft Version:**
 - Version: 1.13.2 Optifine
 - Custom Launcher?: No

**Comment by Deathinflames** [comment]
Oh, this was actually a mistake on my part. I forgot to remove this permission when the testing week had ended. People are not yet supposed to be able to see inside the farmer item yet as the feature is not yet ready to be released.
