### ISSUE TITLE
ESB - Beetroot

### ISSUE THREAD

**Issue by Rockheadryan** [Deathinflames/DoD#31]
**Describe the Issue**
Beetroot doesn't count torwards farming /job or mcmmo

**To Reproduce**
1. Plant beetroot
2. Harvest

**Expected behavior**
I expect to get paid for harvesting the crops and get mcmmo experience.

**Minecraft Version:**
 - Version: 1.13.2 Optifine

**Comment by Fyreheart** [comment]
As far as MCMMO goes.. Beetroots aren't a part of the MCMMO Experience gain.

![](https://i.gyazo.com/707ce0fca7ea68794bf6f2775f7b740d.png)

**Comment by Rockheadryan** [comment]
But why not, they are a crop are they not?

**Comment by Rockheadryan** [comment]
https://github.com/mcMMO-Dev/mcMMO/commit/3ed0fdf330c143b4d2067bace2a829e153b3d948

**Comment by Fyreheart** [comment]
Farmer Job now grants money for harvesting Beetroot.

**Comment by Fyreheart** [comment]
Beetroot now grants MCMMO Experience.
