### ISSUE TITLE
ESB - Cr Claim

### ISSUE THREAD

**Issue by Rockheadryan** [Deathinflames/DoD#32]
**Describe the Issue**
I had my inventory full at the time I tried completed a quest, it told me to use /cr claim to get my rewards. I don't have permission to use the command.

**To Reproduce**
1. Fill inventory
2. Complete /q
3. /cr claim

**Expected behavior**
Get me rewards!

**Screenshots**
![Capture](https://user-images.githubusercontent.com/52331458/60382253-1bf53400-9a26-11e9-9ca5-8aeb9f4e6037.PNG)

**Minecraft Version:**
 - Version: 1.13.2 Optifine
 - Custom Launcher?: No

**Comment by Deathinflames** [comment]
The global alias "/cr" for connecting to the creative server has been removed.

/creative, /plot, /plots are still valid aliases.

**Comment by Rockheadryan** [comment]
Still not able to use command

**Comment by Deathinflames** [comment]
Sorry, It should be good now.
