### ISSUE TITLE
ESB - Auto Farmer

### ISSUE THREAD

**Issue by Rockheadryan** [Deathinflames/DoD#33]
**Describe the bug**
When an Auto Harvester is destroyed by water the growth speed amplifier is not taken away.

**To Reproduce**
1. Place Auto Harvester
2. Break using water

**Expected behavior**
If the Auto Harvester is not there, it should not amplify the growth speed

**Screenshots**
![2019-06-30_15 23 21](https://user-images.githubusercontent.com/52331458/60401704-088fb900-9b4b-11e9-8c7e-bf9ad395a05e.png)
In the image you can see where I had placed one, that spot always grows 10x faster than any other land around it.
**Minecraft Version:**
 - Version: 1.13.2 Optifine_HD_U_E7
 - Custom Launcher?: No

**Comment by Fyreheart** [comment]
Auto Farmers should not be accessible yet. After crafting normal End Rods and placing them, they act as tier 1 growth amplifications, only you can't access the gui. Perhaps disable the recipe for making end rods and remove them from the shop until this can be fixed?

**Comment by Deathinflames** [comment]
A fix for this has been implemented. Waiting to verify issue is resolved before closing ticket.

**Comment by Deathinflames** [comment]
The farm item material has been changed to a different material which should effectively disable any of the previously obtained material items that had the auto farm functionality.

The ability to craft the farm items has also been disabled and the only way to receive an actual auto farm item now is via a console command which was the original intended functionality.

This farm item will be obtainable to players very soon.
