### ISSUE TITLE
ESB - Custom Craft Recipe Suggestions

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#35]
Not able to smelt Stone in a Furnace to create Smooth Stone due to it being a 1.14 feature. Perhaps we can add a custom craft recipe for it?

Two Stone Slabs on top of each other = 1 Smooth Stone
8 Stone + 1 Coal/Charcoal = 8 Smooth Stone

**Comment by Deathinflames** [comment]
You are now able to smelt a regular stone into smooth stone in a furnace.
