### ISSUE TITLE
ESB - Pile of Dust Not Working

### ISSUE THREAD

**Issue by DingoKing** [Deathinflames/DoD#45]
**Describe the bug**
The Pile of Dust from the Jobs shop doesn't give anything when right clicked.

**To Reproduce**
1. Buy a Pile of Dust from the Jobs Shop
2. Right click said Pile of Dust
3. See the item magically vanish from your inventory! 

**Expected behavior**
I'd expect it to give me a new dust...

**Screenshots**
No Screenshots... 
Console does say "Unknown command. Type "/help" for help."
I believe the issue lies in the onRightClick event, where it's making the player use an incorrect command, I just couldn't find where it's detecting that...

**Minecraft Version:**
 - Version 1.13.2
 - Optifine

**Comment by Deathinflames** [comment]
A fix for this has been implemented. :)
