### ISSUE TITLE
ESB - Salmon + Phantom Mobs

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#46]
Players are currently not able to obtain Salmon or Phantom mobs for certain challenges.

I suggest adding Spawn Eggs in the Archer Dungeon loot chest and/or being able to get a biome for naturally spawning Salmon. (River biomes, cold ocean, frozen ocean)

I also suggest removing the mob stacking for fish mobs.

**Comment by Deathinflames** [comment]
The Phantom and Salmon spawn eggs have been added to the Archer Maze loot chest.

All biomes currently in MC 1.13.2 except the Nether and End will be added to /is biomes, soon.

Stacking has been disabled for fish mobs.
