### ISSUE TITLE
ESB - Double Strike error (Custom enchant)

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#53]
This error goes off for Admins when a player uses a sword with Double Strike. The player has Double Strike 3 on their sword.

![doublestrike](https://user-images.githubusercontent.com/42979450/62157304-d48aed80-b2da-11e9-9c41-1405d484fe62.png)

Here is the console error:
> [15:02:41 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "15.0"
> [15:02:41 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:579)
> [15:02:41 INFO]: [AdvancedEnchantments] Extra info: effect[ADD_HARM:15.0]; enchant[doublestrike]; mc[113]; ae[5.8.7]
> [15:02:41 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.

**Comment by Deathinflames** [comment]
It looks like another enchant that can only be a pvp enchant and will not support mobs.
