### ISSUE TITLE
ESB - Killing Quests

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#54]
**Describe the bug**
Zombie Killer quest lets you kill anything and the count goes up for your quest. For example, I can kill pigs and it counts towards the quest.

**To Reproduce**
1. Start the Zombie Killer Quest.
2. Kill any mobs to the required number of kills for the quest.
3. Quest completes even tho you haven't killed any zombies.

Mobs tested - Cows, pigs, villagers.

**Expected behavior**
For the Zombie Killer Quest to require you to kill Zombies, not any mobs.

**Minecraft Version:**
 - Version 1.13.2

**Comment by Fyreheart** [comment]
It could be doing this for all the "kill" quests.
Same thing is happening for the Serial Killer quest for Villagers, and Enderman Reaper quest for Endermen.

**Comment by Deathinflames** [comment]
This looks to have been resolved with the latest QC update.

Please close this ticket if the issue is confirmed to be resolved.

Thanks!
