### ISSUE TITLE
ESB - Biome Additions

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#59]
Request for more Island Biomes.

Mushroom Biome, unlockable perk for $25k.
<s>Swamp Biome, unlockable perk for $10k.</s>
Nether Biome, unlockable perk for $30k.
<s>End Biome, unlockable perk for $50k.</s> - Unlock via End Challenge.
Frozen Ocean Biome for Salmon and Polar Bears - $10k.
Beach Biome for Turtles - $10k.
Taiga for Foxes in the future - $10k
Snowy Taiga for white Foxes in the future - $10k

Still have it cost 100 to change to the biomes, like the rest of them.
Also have a Biomes Pack in the future Token Shop that includes the extra biomes, cost 50 tokens?

**Comment by Rockheadryan** [comment]
Should cost more for end, I'd say around 500,000-2,000,000 cause it'd quickly pay for itself

**Comment by Deathinflames** [comment]
These suggested biomes have been added to the biomes list available to unlock with tokens. For now only Frozen Ocean, Beach, Taiga, and Mushroom will be available. I've decided against adding the end biome to the list due to upcoming planned content.
