### ISSUE TITLE
ESB - Rank 3 Spawner Shop - Villager

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#61]
Upon obtaining Skyblock Rank 3, you gain access to purchase Villager Spawners from the Items Shop. However, the button does not show correctly until you unlock an even amount of Spawners. The player can currently get around this by clicking the glass pane shown in the screenshot to purchase Villager Spawners.

![spawnershop](https://user-images.githubusercontent.com/42979450/63066945-ac0a1280-beda-11e9-8186-3b1fafa07a42.png)
![spawnershop 2](https://user-images.githubusercontent.com/42979450/63066948-af050300-beda-11e9-9cf5-46f6da56ea8b.png)

**Comment by Deathinflames** [comment]
Implemented a more user friendly and more intuitive design for the spawner shop.
