### ISSUE TITLE
ESB - Headless Mob Heads

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#63]
This is regarding Heads obtained from the Headless custom enchant.

If possible, it would be nice if the Headless enchant could give actual Minecraft mob heads instead of the Heads Database heads for Skeletons, Zombies, and Creepers. I don't know if this is configurable with the Enchants?

It is also strange because some heads that should stack together don't. They look the exact same, but don't stack together.

**Comment by Deathinflames** [comment]
A fix for this issue has been implemented and requires testing. Automatically closing ticket if no responses are made after some time has passed.
