### ISSUE TITLE
ESB - Quests, Click To Start instead of QUEST COMPLETE

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#64]
After completing the Enchanter I quest, it does not properly say the Reset time on the hover-over. It DOES tell you in chat if you "click to start" tho.

What the proper hover-over would show:
![](https://i.gyazo.com/31768b66ddd4c76783fe17bc6c55a999.png)

Enchanter I hover-over after completing quest:
![](https://i.gyazo.com/7c3c13ce856164de7c1e9c53aa431ebf.png)

In chat when clicking to start the quest again if you've already done it:
![](https://i.gyazo.com/239c5f94fac7be6ac360af3e1efa010b.png)

**Comment by Fyreheart** [comment]
The Fisherman I quest also does this.

**Comment by Deathinflames** [comment]
This issue has been confirmed fixed for the enchanter quest, also fixed for fisherman but still requires confirmation. Please re-open this ticket if the fisherman quest is still not updating correctly when on cooldown.
