### ISSUE TITLE
ESB - Hopper Link Timing

### ISSUE THREAD

**Issue by Rockheadryan** [Deathinflames/DoD#66]
**Describe the issue**
Hopper linking time is random. Sometimes its 10 seconds, sometimes its .5 seconds

**To Reproduce**
1. Click link output while in a hopper
2. Let it time out, repeat and see the discrepancy 

**Expected behavior**
Hopper link should be one set amount of time

**Minecraft Version:**
 - Version [e.g. 1.13.2 Optifine_HD_U_E5]
 - Custom Launcher?: No

**Additional context**
This happens both when you're linking output, and when linking blacklist.

**Comment by Deathinflames** [comment]
Is this still happening after the update hoppers received on September 5th?

**Comment by Deathinflames** [comment]
A fix has been implemented for hopper container linking issues and improved the overall hopper linking system to be more intuitive.
