### ISSUE TITLE
ESB - OreGen Issues

### ISSUE THREAD

**Issue by Rockheadryan** [Deathinflames/DoD#67]
**Describe the bug**
OreGen doesn't work properly with flooded blocks.

**To Reproduce**
1. Make cobble generator like the one in the picture
2. Break the cobble

**Expected behavior**
Ores should be generated

**Screenshot**
![2019-08-17_01 21 55](https://user-images.githubusercontent.com/52331458/63207623-dac8ea00-c08e-11e9-9c84-20427cea84c4.png)

Video: https://youtu.be/JtdCfdJX9ns
**Minecraft Version:**
 - Version [e.g. 1.13.2 Otifine_HD_U_E5]
 - Custom Launcher?: No

**Comment by Deathinflames** [comment]
Thanks for the detailed report, especially the YT video accurately showcasing the issue! I have forwarded this information to the corresponding developer for resolution.

You can track the status here: https://git.spaceio.xyz/Spigot_Plugins/AdvancedOreGen/issues/13

**Comment by Deathinflames** [comment]
Is this still happening after the update hoppers received on September 5th?

**Comment by Deathinflames** [comment]
Is this still happening after the update the oregen received on September 5th?

**Comment by Deathinflames** [comment]
After 6 months of waiting, the dev has not expressed much interest in resolving this particular issue and therefore it is my assumption that this may never be fixed how we want it. However, as an alternative the dev has provided a workaround by making it possible to use a fence post as a lava source.
