### ISSUE TITLE
USB - "/voteinfo 3" shows diamonds instead of emeralds

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#8]
Update "/voteinfo 3" to show emeralds as reward instead of diamonds.

**Comment by Deathinflames** [comment]
On which server? Title states "diamonds instead of emeralds" and description shows "emeralds instead of diamonds".

**Comment by Fyreheart** [comment]
On USB. Sorry. 
Yes, it currently shows diamonds. Needs to be updated to show emeralds.

**Comment by Deathinflames** [comment]
This has been updated.
