### ISSUE TITLE
ESB - Farmer I messages wron for Sugar Cane

### ISSUE THREAD

**Issue by LupoSan** [Deathinflames/DoD#81]
**Describe the bug**
For the Farmer I quest, the 3rd step is to "Harvest 50 Sugarcane" However, after the message appears that says this is the step you are on, when you type /q to look at the quest it says you should be Harvesting 50 Watermelon which was actually the first step. Also, It doesn't increase the counter when you harvest Watermelon or Sugarcane. It only increases the counter when you PLANT Sugarcane.

**To Reproduce**
1. When the Farmer I quest becomes available type /q to bring up the quests
2. Click on the Farmer I quest to select it
3. Complete the 1st 2 steps so that the current step you are working on should be "Harvest 50 Sugarcane"
4. Type /q
5. Click the Farmer I quest
6. See that the current step is listed as Harvest 50 Watermelon
7. Exit quest screen
8. Harvest some Sugarcane
9. Type /q
10. Click the Farmer I quest
11. See that the count does not go up
12. Exit the quest screen
13. Harvest some Watermelon.
14. Type /q
15. Select the Farmer I quest
16. See that the count does not go up
17. Exit the quest screen
18. Plant Sugar can in an appropriate spot
19. Type /q
20. Click on Farmer I quest
21. See that the count went up.

**Expected behavior**
The current quest should read "Harvest 50 Sugarcane" and the count should go up when harvesting Sugarcane. Alternately, quest step and the current quest should read "Plant 50 Sugarcane" then the current count going up when planting Sugarcane will be correct.

**Screenshots**
Sorry, didn't know about GitHub until the day after the bug and didn't think of getting a screenshot, will do so next time.

**Minecraft Version:**
 - Version [e.g. 1.13.2]

**Comment by Fyreheart** [comment]
Fixed the description for the Sugar Cane step in the Quest. Thanks for reporting!
