### ISSUE TITLE
ESB - /anvil

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#84]
When a player does the /anvil command, first it tells them unknown command, then tells them the second time that they must wait 24 hours.

Unsure if it actually repairs the intended item.

![](https://cdn.discordapp.com/attachments/192038277149229058/692564189960601680/unknown.png)

**Comment by 99FireyMan99** [comment]
It does NOT repair the item.

**Comment by Deathinflames** [comment]
This issue has been resolved. Thanks for reporting it!
