### ISSUE TITLE
ESB - /homes

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#85]
Make it only say your number of homes when you do "/home" or "/homes" and not when you "/home (name)" or "/delhome" or similar command.

![homes](https://user-images.githubusercontent.com/42979450/80670245-672c0900-8a74-11ea-9d43-cdbb802b4f2b.png)

**Comment by Deathinflames** [comment]
Adjusted this functionality, let me know if it needs any further tweaking. :)
