### ISSUE TITLE
CR - Museum Modifications

### ISSUE THREAD

**Issue by ghost** [Deathinflames/DoD#86]
**Describe the bug**
List of actions I can perform within the archived spawn, which may or may not be desired:
- Place minecarts (and variants) onto rails.
- Break item frames.
- Break paintings.
- Place item frames.
- Place paintings.
- Launch fireworks.
- Open and insert/remove items from containers (brewing stands, shulker boxes, dispensers, droppers, enderchests (secretly chests), etc.)
- Use jukeboxes.
- Teleport via enderpearl and chorus fruit.
- Place armour stands.
- Break armour stands.
- Place items into flower pots.
- Place end crystals.
- Destroy end crystals.
- Throw eyes of ender.

What I cannot do:
- Use anvils.
- Place boats.
- Use enchantment tables.
- Use signs (obviously).
- Break most blocks (excluding those recognized as entities).
- Place most blocks.
- Destroy water via bucket or sponge.
- Play or alter the tune of note blocks.
- Use buttons.
- Ride in minecarts.
- Fill or empty cauldrons.
- Open trapdoors.
Also, all chests appear to be converted into enderchests.

**Minecraft Version:**
1.12.2

**Comment by Deathinflames** [comment]
Permissions in the museum worlds have been adjusted.

"Also, all chests appear to be converted into enderchests."
You must connect with the latest version of MC to avoid this visual bug.
