### ISSUE TITLE
CR - Cannot purchase Creative Item with Tokens

### ISSUE THREAD

**Issue by ghost** [Deathinflames/DoD#88]
**Describe the bug**
Purchasing perk 'Pet Skeleton' is not possible with 15 tokens, despite indicating otherwise.  
https://cdn.discordapp.com/attachments/645730398956945408/877955590792556554/Yaye_22.mp4
**Minecraft Version: 1.12.2**

**Comment by Deathinflames** [comment]
This issue has been resolved.
