### ISSUE TITLE
CR - Chat Lists Incorrect Token Shop Perk

### ISSUE THREAD

**Issue by ghost** [Deathinflames/DoD#90]
**Describe the bug**
I purchased sign colours, but chat reads otherwise. The effect listed within the GUI is correct, however.
![image](https://user-images.githubusercontent.com/40145743/130278943-2083e394-be95-491b-a80c-722f79cb7359.png)
![image](https://user-images.githubusercontent.com/40145743/130278952-682a195d-4f9f-4a36-9c5d-4bf81055e3f2.png)

**Minecraft Version: 1.12.2**

**Comment by Deathinflames** [comment]
Fixed the typo.
