### ISSUE TITLE
CR - Dead Bush is Funky

### ISSUE THREAD

**Issue by ghost** [Deathinflames/DoD#91]
For some unknown reason, I cannot drop a dead bush within the creative mode server (both archives and plots). I can delete it from the menu, however. Stranglely, once dropped by any means, it's deleted immediately, unlike other items. Also unlike other items, when placing it onto illegal terrain (as in, terrain which requires admin perms), it disappears from my inventory. If this wasn't enough, I cannot place them onto valid terrain, either (excluding flower pots, but including item frames). What's the trouble with a dead bush, of all items?

**Minecraft Version: 1.12.2**

**Comment by Deathinflames** [comment]
This bug is related to connecting with versions below the recommended version and does not occur when using 1.17+
