### ISSUE TITLE
CR - Elytra Upwards flight Kick

### ISSUE THREAD

**Issue by ghost** [Deathinflames/DoD#93]
**Describe the bug**
Travelling upwards at a certain speed via elytra and fireworks kicks you into the hub, with the error 'Invalid move player packet received.' At least, this applies to the creative server. A single firework, perhaps two, fired upwards is generally sufficient to activate the error.

**Minecraft Version: 1.12.2**

**Comment by ghost** [comment]
This issue appears to occur within Minecraft itself, rather than as server-specific error. See MC-122354. However, examining if it continues to occur within other versions would ensure this.

**Comment by Deathinflames** [comment]
In addition to this being a MC bug, the anti-cheat could also be getting triggered through inappropriate use of Elytra and is therefore working as intended to prevent abuse.
